variables:
  IMAGE_NAME: ghcr.io/arlcrow/lisiywebsite

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_TAG_BRANCH: ""
    IMAGE_TAG_COMMIT: ""
    DOCKERFILE_PATH: Dockerfile
  before_script:
    - mkdir -pv /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(printf "%s:%s" "arlcrow" "${GITHUB_CI_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $DOCKERFILE_PATH
      --destination $IMAGE_TAG_BRANCH
      --destination $IMAGE_TAG_COMMIT
      --cache=true
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        IMAGE_TAG_BRANCH: $IMAGE_NAME:${CI_COMMIT_TAG#v}
        IMAGE_TAG_COMMIT: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      exists:
        - $DOCKERFILE_PATH
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        IMAGE_TAG_BRANCH: $IMAGE_NAME:latest
        IMAGE_TAG_COMMIT: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      exists:
        - $DOCKERFILE_PATH
    - if: $CI_COMMIT_BRANCH
      variables:
        IMAGE_TAG_BRANCH: $IMAGE_NAME:branch-$CI_COMMIT_REF_SLUG
        IMAGE_TAG_COMMIT: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      exists:
        - $DOCKERFILE_PATH
