stages:
  - docker_build
  - deploy

docker_build_master:
  image: registry-mirror.arlcrow.site/library/docker:latest
  services:
    - registry-mirror.arlcrow.site/library/docker:dind
  stage: docker_build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest .
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:latest
  only:
    - master

docker_build_other:
  image: registry-mirror.arlcrow.site/library/docker:latest
  services:
    - registry-mirror.arlcrow.site/library/docker:dind
  stage: docker_build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH .
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH
  except:
    - master

deploy_master:
  stage: deploy
  image:
    name: registry.arlcrow.site/docker-images/ubuntu:latest
  script:
    - echo passed
  only:
    - master
