stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
        docker build --cache-from=$CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:latest .
        docker push $CI_REGISTRY_IMAGE:latest
      else
        docker build --cache-from=$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH .
        docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH != "master"

deploy:
  stage: deploy
  image:
    name: kroniak/ssh-client:latest
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  script:
    - ssh $SSH_OTHER $SSH_USER@$SSH_HOST $SSH_SCRIPT
  only:
    - master
